export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED';
export const PURSCHASE_BURGER_START='PURSCHASE_BURGER_START';
export const PURSCHASE_BURGER_SUCCESS='PURSCHASE_BURGER_SUCCESS';
export const PURSCHASE_BURGER_FAIL='PURSCHASE_BURGER_FAIL'